from typing import Any

class QObject:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QThread:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def start(self) -> None: ...

class QTimer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
