from typing import Any, Iterable

float32: Any
ndarray = Any

def count_nonzero(a: Any, axis: int | None = ...) -> int: ...
def max(a: Any, axis: int | None = ...) -> Any: ...
def abs(a: Any) -> Any: ...
def concatenate(arrays: Iterable[Any], axis: int | None = ...) -> Any: ...
def mean(a: Any, axis: int | None = ...) -> Any: ...
def std(a: Any, axis: int | None = ...) -> Any: ...
def min(a: Any, axis: int | None = ...) -> Any: ...
